### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by NoNameProvided** [typestack/class-validator#178]
There are quite a few things we should fix/implement before releasing 1.0, some of these will be a breaking change.

> Note: this issue will be updated as progress is made towards these goals.

- [ ] **Features**
  - [ ] adding `ValidationError.toString()` (#26)
  - [ ] experimenting to see if we can add support for class method validation (#115)
  - [ ] rethink how groups are handled
  - [ ] experimenting to see if we can add support for dynaimc constraints (#76)
- [ ] **Schema based validation**
  - [ ] fix current bugs
  - [ ] add test coverage
  - [ ] make every validator available 
  - [ ] add option to generate JSON schema from class metadata
  - [ ] add support of registering validation schema for target class
  - [ ] add support of registering custom validations without using decorators
- [ ] **Documentation**
  - [ ] split up docs into sections
  - [ ] add a documentation site 
  - [ ] add documentation for usage with pure JS
  - [ ] add documentation for usage with babel + decorators
  - [ ] add documentation about using error output with Angular's Reactive Forms module
  - [ ] add better docs about custom decorators and validation classes
- [ ] **Project setup refactor**
  - [ ] split up files, better code oraganziation
  - [ ] add Prettier for code formatting
  - [ ] add husky for auto formatting and running tests before commits
- [ ] **Test setup refactor**
  - [ ] move to Jest (batteries included and out-of-box TS support)
  - [ ] split test files and move them next to the components they test

--- 

**Please do not comment things like "+1" or "Me too"**, but feel free to add your voice.

**Comment by luqezman** [comment]
Awesome. Waiting for `rethink how groups are handled` MUAHAHAHA :D Love u guys.

**Comment by yantrab** [comment]
about (#69)
[this ](https://github.com/yantrab/nest-angular/blob/master/client/src/app/auth/auth.component.ts)is how i do it.

**Comment by dsbert** [comment]
It is not encouraging that in two years, only one checkbox has been checked on this list and the project is still on version 0.11.0 (released 15 months ago).

**Comment by glen-84** [comment]
@NoNameProvided,

> add validation modes (fail on first error) (#148)

Is this resolved by #620?

**Comment by ytetsuro** [comment]
@NoNameProvided 

> add validation modes (fail on first error)

This is fixed.

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
This repo is DEAD.. no ones (except bot) maintains it..
I think you should allow more users to maintain it.. approve PRs etc...

**Comment by hood** [comment]
@NoNameProvided and @pleerock do you have any plans on including more people as maintainers for this project? This is getting ridiculous. There is still a lot of work to be done on this repository, and keeping this situation stale is not going to help in any way. Please don't let this end up like TypeORM did.

**Comment by nodejsdeveloperskh** [comment]
@NoNameProvided please fix this issue. it is a very annoying and discussing error. i am tired, because of the `whitelist` I force to copy and paste my code multiple places and this is a very bad practice. 

https://github.com/typestack/class-validator/issues/1288
